# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ruby-git}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Stefan Penner"]
  s.date = %q{2010-04-04}
  s.description = %q{simple ruby wrapper around git}
  s.email = %q{stefan.penner@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/commands/all.rb",
     "lib/commands/authors.rb",
     "lib/commands/defaults.rb",
     "lib/commands/log.rb",
     "lib/commands/ls.rb",
     "lib/commands/ls_to_hash.rb",
     "lib/commands/repo_history.rb",
     "lib/commands/shortlog.rb",
     "lib/helpers/ls_tree_to_hash.rb",
     "lib/ruby-git.rb",
     "ruby-git.gemspec",
     "test/helper.rb",
     "test/test_ruby-git.rb"
  ]
  s.homepage = %q{http://github.com/stefanpenner/ruby-git}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{simple ruby wrapper around git}
  s.test_files = [
    "test/helper.rb",
     "test/test_ruby-git.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    else
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
  end
end

